version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www/html
      - ./deploy/local.ini:/usr/local/etc/php/conf.d/local.ini
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./deploy/nginx/conf.d/:/etc/nginx/conf.d/
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "33060:3306"
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: heytutor
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: heytutor
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
      - ./deploy/mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  db_data:
