version: "3.8"

networks:
  app-network:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./deploy/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: sh -c "while ! nc -z db 3306; do sleep 1; done && php artisan migrate && php artisan db:seed && php-fpm"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "33060:3306"
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: heytutor
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: heytutor
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
      - ./deploy/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./deploy/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
volumes:
  db_data:
    driver: local
